apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                # - alertmanager:9093
    
    rule_files:
    
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: [ "localhost:9090" ]
      - job_name: "cadastrocliente"
        metrics_path: "/actuator/prometheus"
        scrape_interval: 3s
        static_configs:
          - targets: ["localhost:8080"]
      - job_name: "postexporter"
        scrape_interval: 3s
        static_configs:
          - targets: [ "localhost:9187" ]