apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-cliente-app
  labels:
    app: cadastro-cliente-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadastro-cliente-app
  template:
    metadata:
      name: cadastro-cliente-app
      labels:
        app: cadastro-cliente-app
    spec:
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          emptyDir: {}
      containers:
        - name: cadastro-cliente-app
          image: gustavo4642/cadastro-cliente-app:0.1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 5
          livenessProbe:
              httpGet:
                port: 8080
                path: /actuator/health
        - name: dbteste
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "4642941"
          ports:
            - containerPort: 5432
          imagePullPolicy: IfNotPresent
        - name: app-prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
        - name: grafana
          image: grafana/grafana-enterprise
          ports:
            - containerPort: 3000
        - name: postexporter
          image: quay.io/prometheuscommunity/postgres-exporter:latest
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:4642941@localhost:5432?ssl=disable"
          ports:
            - containerPort: 9187
          imagePullPolicy: IfNotPresent
      restartPolicy: Always