apiVersion: v1
kind: Service
metadata:
  name: cad-cli-nodeport
spec:
  type: NodePort
  selector:
    app: cadastro-cliente-app
  ports:
  - protocol: TCP
    name: 'aplicacao'
    nodePort: 31001 
    port: 8080
  - protocol: TCP
    name: 'bancodedados'
    nodePort: 31432
    port: 5432
#  - protocol: TCP
#    name: 'prometheus'
#    nodePort: 31090
#    port: 9090
#  - protocol: TCP
#    name: 'postexporter'
#    nodePort: 31187
#    port: 9187
  - protocol: TCP
    name: 'grafana'
    nodePort: 30000
    port: 3000
