apiVersion: v1
kind: Pod
metadata:
  name: db-clientes
  labels:
    app: db-clientes
spec:
  containers:
    - name: db-clientes
      image: postgres:latest
      env:
        - name: POSTGRES_PASSWORD
          value: "4642941"
      ports:
        - containerPort: 5432
      imagePullPolicy: IfNotPresent
  restartPolicy: Always